version: '3.1'

networks:
  shared-network:
    driver: bridge

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=retail
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - retail-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - shared-network

  web:
    build:
      context: ./
      dockerfile: Dockerfile_compose
    links:
      - 'db:database'
    environment:
      - RETAIL_PORT=8080
      - RETAIL_DIAG_PORT=8181
      - RETAIL_DATABASE_URL=postgres://docker:docker@db:5432/retail?pool_max_conns=10
    ports:
      - '8080:8080'
      - '8081:8181'
    depends_on:
      - dbmigration
    networks:
      - shared-network

  dbmigration:
    build: database/
    links:
      - 'db:database'
    environment:
      - HOST=database
      - PORT=5432
    networks:
      - shared-network

volumes:
  retail-data: # named volumes can be managed easier using docker-compose
