version: '3.1'

networks:
  shared-network:
    driver: bridge

volumes:
  retail-data: # named volumes can be managed easier using docker-compose

services:
  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=retail
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - retail-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - shared-network

  dbmigration:
    build: cmd/retail-sample/internal/persistence/postgres/migration
    depends_on: 
    - db
    environment:
      - HOST=db
      - PORT=5432
    networks:
      - shared-network
