version: '3.6'

networks:
  shared-network:
    driver: bridge

volumes:
  retail-data: # named volumes can be managed easier using docker-compose

services:
  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=retail
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - retail-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - shared-network

  ui:
    ports:
      - '1234:1234'
    build: web/
    depends_on:
      - db

  tern:
    build: cmd/retail-sample/internal/persistence/postgres/migration
    depends_on:
      - ui
    environment:
      - HOST=db
      - PORT=5432     
      - POSTGRES_DB=retail
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    networks:
      - shared-network