# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

@host = http://localhost:8080

### Create inventory item
POST {{host}}/inventory
Content-Type: application/json

{
  "name": "garlic"
}

### Get one inventory item
GET {{host}}/inventory/1
Accept: application/json

### List inventory items
GET {{host}}/inventory
Accept: application/json

### Disable inventory item
PATCH {{host}}/inventory/1
Accept: application/json

{
  "enabled": false
}

### List orders
GET {{host}}/order
Accept: application/json

### Show stock
GET {{host}}/stock/1
Accept: application/json

### Provision stock
POST {{host}}/stock/1
Content-Type: application/json

{
  "qty":14
}

### List recipes
GET {{host}}/recipe
Accept: application/json

### Create recipe
POST {{host}}/recipe
Content-Type: application/json

{
  "name": "garlic bread",
  "items": {
    "1": 5
  }
}

### List orders
GET {{host}}/order
Accept: application/json

### Place new order
POST {{host}}/order
Content-Type: application/json

{
  "id": 2,
  "qty": 1
}
