# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST localhost:8080/order
Content-Type: application/json

{
  "id":"1",
  "qty":"2"
}

###
GET http://localhost:8080/inbound/config
Accept: application/json

###

POST http://localhost:8080/inbound/config
Content-Type: application/json

["gold", "silver"]

###

PATCH http://localhost:8080/inbound/config/gold/disable

###

GET http://localhost:8080/inbound/config/gold
Accept: application/json

###

GET http://localhost:8080/outbound

###

GET http://localhost:8080/stock

###
