name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Deps
      run: |
        go get -v -t -d ./...
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test

    - name: Vet
      run: go vet ./...

