name: All in one

on: push

jobs:
  docker:
    runs-on: docker.pkg.github.com/anatollupacescu/retail-sample/v0.0.1:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build & Push to GitHub Package
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          REGISTRY: "docker.pkg.github.com"
          IMAGE_NAME: "${{ secrets.GITHUB_USERNAME }}/retail-sample"
          TAG_NAME: "build"
          LATEST: "true"
